### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by CanerKocak** [SysLogica/w98-mono#19]
I encountered some difficulties while attempting to run the repository. It appears that certain dependencies were missing from the package.json file within the workspaces. The following steps allow for a succesfull deployment for me now

```bash
  yarn -v # make sure you're using yarn 4 eg: 4.2.2
  
  dfx start --clean --background

  # Install js deps, run initialization script and deploy canisters
  yarn install
  yarn local:init
  yarn local:deploy
```

earlier I faced issues like these:
```
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: website@0.0.0 
npm ERR!   at location: /Users/caner/w98-mono-1/src/frontends/website
```

If possible, I would appreciate it if you could investigate this matter further. I prefer not to manually add and place dependencies using a hardcoded approach, but I can now say that it runs on my machine xd

**Comment by nolyoi** [comment]
Ok I updated the readme, hopefully that works from a fresh start now
